name: Prisonbeds
version: 0.1.2
description: Type "/pbset" to set the respawn point of the next player you kill. Sleep in a bed to change your respawn point back to the bed. Not persistant. Untested. Probably incredibly buggy.
author: cxschx
authors: [cxschx, Exultant]

main: com.untamedears.Prisonbeds.Prisonbeds
database: false

commands:
  pbset:
    description: Sets a prison for the next player you kill.
    usage: /pbset
  pbunset:
    description: Unsets your primed prison.
    usage: /pbunset
  pbinfo:
    description: Gets information on your currently primed prison.
    usage: /pbinfo
  pbhelp:
    description: Help for Prisonbeds.
    usage: /pbhelp